CREATE SCHEMA DUMMY;

CREATE TABLE DUMMY.DUMMYTABLE(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    dummy VARCHAR(255) NOT NULL

);

INSERT INTO DUMMY.DUMMYTABLE(dummy)
VALUES("JUSTINE"),("GARETT"),("ANA"),("Logan");


SELECT * FROM DUMMY.DUMMYTABLE;
